.TH "c.DetailsPlaces.DetailsPlaces" 3 "Thu Feb 5 2015" "Version 0.1" "Dream Park" \" -*- nroff -*-
.ad l
.nh
.SH NAME
c.DetailsPlaces.DetailsPlaces \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits CreaParking\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, main, parking)"
.br
.ti -1c
.RI "def \fBvalider\fP (self)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Dream Park from the source code\&.
