.TH "c.Teleporteur.Teleporteur" 3 "Thu Feb 5 2015" "Version 0.1" "Dream Park" \" -*- nroff -*-
.ad l
.nh
.SH NAME
c.Teleporteur.Teleporteur \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBteleporterVoiture\fP (voiture, place)"
.br
.ti -1c
.RI "def \fBteleporterVoitureSuperAbonne\fP (voiture, parking)"
.br
.ti -1c
.RI "def \fBteleporterVersSortie\fP (placement)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Dream Park from the source code\&.
