.TH "Client" 3 "Fri Feb 6 2015" "Version 0.1" "Dream Park" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Client \- Module qui implémente les classes representants un client de DreamPark\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Module qui implémente les classes representants un client de DreamPark\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Dream Park from the source code\&.
