.TH "m.Client.TypeAbonnement" 3 "Thu Feb 5 2015" "Version 0.1" "Dream Park" \" -*- nroff -*-
.ad l
.nh
.SH NAME
m.Client.TypeAbonnement \- Classe définissant les constante de typeAbonnment disponible pour le client\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBABONNE\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Classe définissant les constante de typeAbonnment disponible pour le client\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Dream Park from the source code\&.
