.TH "m.Client" 3 "Thu Feb 5 2015" "Version 0.1" "Dream Park" \" -*- nroff -*-
.ad l
.nh
.SH NAME
m.Client \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBClient\fP"
.br
.RI "\fIReprésentation d'un client de DreamPark\&. \fP"
.ti -1c
.RI "class \fBTypeAbonnement\fP"
.br
.RI "\fIClasse définissant les constante de typeAbonnment disponible pour le client\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Module qui implémente les classees reprensentants un client de DreamPark.

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Dream Park from the source code\&.
