.TH "m.Parking" 3 "Thu Feb 5 2015" "Version 0.1" "Dream Park" \" -*- nroff -*-
.ad l
.nh
.SH NAME
m.Parking \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBParking\fP"
.br
.RI "\fIRepresentation d'un parking de DreamPark\&. \fP"
.ti -1c
.RI "class \fBPlace\fP"
.br
.RI "\fIRepresentation d'une place de DreamPark\&. \fP"
.ti -1c
.RI "class \fBPlacement\fP"
.br
.RI "\fIRepresentation d'un \fBPlacement\fP de DreamPark\&. \fP"
.ti -1c
.RI "class \fBTypePlace\fP"
.br
.RI "\fIRepresentation d'un typePlace de DreamPark\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    Module qui implémente les classees reprensentants un parking de DreamPark.

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Dream Park from the source code\&.
