.TH "m.Service.Service" 3 "Thu Feb 5 2015" "Version 0.1" "Dream Park" \" -*- nroff -*-
.ad l
.nh
.SH NAME
m.Service.Service \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBid\fP (self)"
.br
.ti -1c
.RI "def \fBtypeService\fP (self)"
.br
.ti -1c
.RI "def \fBplacement\fP (self)"
.br
.ti -1c
.RI "def \fBinfo\fP (self)"
.br
.ti -1c
.RI "def \fBestRealise\fP (self)"
.br
.ti -1c
.RI "def \fBdoService\fP (self)"
.br
.ti -1c
.RI "def \fBnonRealise\fP (self)"
.br
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBgetAllEnCours\fP (parking)"
.br
.ti -1c
.RI "def \fBgetAllServicePlacement\fP (placement)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtypeService\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Dream Park from the source code\&.
