.TH "m.Voiture.Voiture" 3 "Thu Feb 5 2015" "Version 0.1" "Dream Park" \" -*- nroff -*-
.ad l
.nh
.SH NAME
m.Voiture.Voiture \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBsetClient\fP (self, client)"
.br
.ti -1c
.RI "def \fBid\fP (self)"
.br
.ti -1c
.RI "def \fBhauteur\fP (self)"
.br
.ti -1c
.RI "def \fBlongueur\fP (self)"
.br
.ti -1c
.RI "def \fBimmatriculation\fP (self)"
.br
.ti -1c
.RI "def \fBclient\fP (self)"
.br
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Dream Park from the source code\&.
