.TH "src.c.Parking.DetailsPlaces" 3 "Sun Feb 8 2015" "Version 1.0" "Dream Park" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.c.Parking.DetailsPlaces \- Controleur d'affichage des details des places d'un parking existant\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsrc\&.c\&.Parking\&.CreaParking\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, main, parking)"
.br
.RI "\fIContructeur\&. \fP"
.ti -1c
.RI "def \fBvalider\fP (self)"
.br
.RI "\fIGestion de retour sur le fenetre principal\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Controleur d'affichage des details des places d'un parking existant\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.c\&.Parking\&.DetailsPlaces\&.__init__ ( self,  main,  parking)"

.PP
Contructeur\&. 
.PP
\fBParameters:\fP
.RS 4
\fImain\fP Controleur parent 
.br
\fIparking\fP praking dont on veux afficher le détail 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Dream Park from the source code\&.
