.TH "src.m.TypeAbonnement.TypeAbonnement" 3 "Mon Jan 12 2015" "Version 0.1" "Dream Park" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.m.TypeAbonnement.TypeAbonnement \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBABONNE\fP = 0"
.br
.ti -1c
.RI "int \fBSUPER_ABONNE\fP = 1"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Dream Park from the source code\&.
