.TH "src.m.test.TestParking.TestPlace" 3 "Sun Feb 8 2015" "Version 1.0" "Dream Park" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.m.test.TestParking.TestPlace \- Test Place\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBTestPlace\fP (self)"
.br
.RI "\fITest instanciation\&. \fP"
.ti -1c
.RI "def \fBTestPrendreLiberer\fP (self)"
.br
.RI "\fITest de pendre et liberer les places\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Test Place\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Dream Park from the source code\&.
