.TH "src.m.test.TestVoiture.TestVoiture" 3 "Sun Feb 8 2015" "Version 1.0" "Dream Park" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.m.test.TestVoiture.TestVoiture \- Test \fBVoiture\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBTestVoiture\fP (self)"
.br
.RI "\fITest instanciation\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Test \fBVoiture\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Dream Park from the source code\&.
