.TH "src.m.test.TestAbonnement.TestClient" 3 "Sun Feb 8 2015" "Version 1.0" "Dream Park" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.m.test.TestAbonnement.TestClient \- Test Client\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBTestClient\fP (self)"
.br
.RI "\fITest Instanciations\&. \fP"
.ti -1c
.RI "def \fBTestMaj\fP (self)"
.br
.RI "\fITest mise a jour Client\&. \fP"
.ti -1c
.RI "def \fBTestDesabo\fP (self)"
.br
.RI "\fITest desabonnement\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Test Client\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Dream Park from the source code\&.
