.TH "src.m.connexionBDD.connexionBDD" 3 "Mon Jan 12 2015" "Version 0.1" "Dream Park" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.m.connexionBDD.connexionBDD \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBseDeconnecter\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBchemin\fP"
.br
.ti -1c
.RI "\fBconn\fP"
.br
.ti -1c
.RI "\fBcur\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Dream Park from the source code\&.
