.TH "src.m.ListeTypePlace.ListeTypePlace" 3 "Mon Jan 12 2015" "Version 0.1" "Dream Park" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.m.ListeTypePlace.ListeTypePlace \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBadd\fP (self, h, l, nb)"
.br
.ti -1c
.RI "def \fBnbPlaceTotal\fP (self)"
.br
.ti -1c
.RI "def \fBliste\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    Classe qui permet de définir une liste de type de place par niveau pour la création d'un parking

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Dream Park from the source code\&.
