.TH "src.m.Abonnement" 3 "Sun Feb 8 2015" "Version 1.0" "Dream Park" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.m.Abonnement \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBClient\fP"
.br
.RI "\fIReprésentation d'un \fBClient\fP de DreamPark\&. \fP"
.ti -1c
.RI "class \fBTypeAbonnement\fP"
.br
.RI "\fIClasse définissant les constantes de \fBTypeAbonnement\fP disponible pour le \fBClient\fP\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    Module qui implémente les classes representants les Abonnements de DreamPark.

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Dream Park from the source code\&.
