.TH "src.v.MyQt" 3 "Sun Feb 8 2015" "Version 1.0" "Dream Park" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.v.MyQt \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMyQMainWindow\fP"
.br
.RI "\fIQMainWindow personnalisé \fP"
.ti -1c
.RI "class \fBMyQWidget\fP"
.br
.RI "\fIQWydget personnalisé \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    Module de Gestion personnalisée d'élément Qt

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Dream Park from the source code\&.
