.TH "src.m.Client.TypeAbonnement" 3 "Fri Feb 6 2015" "Version 0.1" "Dream Park" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.m.Client.TypeAbonnement \- Classe définissant les constantes de \fBTypeAbonnement\fP disponible pour le \fBClient\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBABONNE\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Classe définissant les constantes de \fBTypeAbonnement\fP disponible pour le \fBClient\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Dream Park from the source code\&.
