.TH "src.m.test.TestParking.TestTypePlace" 3 "Sun Feb 8 2015" "Version 1.0" "Dream Park" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.m.test.TestParking.TestTypePlace \- Test Types Places\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBTestTypePlace\fP (self)"
.br
.RI "\fITest Instanciation\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Test Types Places\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Dream Park from the source code\&.
