.TH "src.m.Placement.Placement" 3 "Mon Jan 12 2015" "Version 0.1" "Dream Park" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.m.Placement.Placement \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, voiture, place)"
.br
.ti -1c
.RI "def \fBend\fP (self)"
.br
.ti -1c
.RI "def \fBid\fP (self)"
.br
.ti -1c
.RI "def \fBestEnCours\fP (self)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBget\fP (id)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "list \fBplacements\fP = []"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.m\&.Placement\&.Placement\&.__init__ ( self,  voiture,  place)"

.PP
.nf
Creer un placement
:param voiture: Voiture
:param place: Place
:return:

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def src\&.m\&.Placement\&.Placement\&.get ( id)\fC [static]\fP"

.PP
.nf
Recupere le Placement d'id id
:param id: str
:return: Placement or None

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Dream Park from the source code\&.
