.TH "src.c.Teleporteur.Teleporteur" 3 "Sun Feb 8 2015" "Version 1.0" "Dream Park" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.c.Teleporteur.Teleporteur \- Gestion de teleportation de Voiture\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBteleporterVoiture\fP (voiture, place)"
.br
.RI "\fITeleportation d'une Voiture d'un Client standard\&. \fP"
.ti -1c
.RI "def \fBteleporterVoitureSuperAbonne\fP (voiture, parking)"
.br
.RI "\fITeleportation d'une Voiture d'un superAbo\&. \fP"
.ti -1c
.RI "def \fBteleporterVersSortie\fP (placement)"
.br
.RI "\fITeleportation de la voiture vers la sortie\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Gestion de teleportation de Voiture\&. 
.SH "Member Function Documentation"
.PP 
.SS "def src\&.c\&.Teleporteur\&.Teleporteur\&.teleporterVersSortie ( placement)\fC [static]\fP"

.PP
Teleportation de la voiture vers la sortie\&. 
.PP
\fBParameters:\fP
.RS 4
\fIplacement\fP Placement de la Voiture que l'on veut sortir 
.RE
.PP

.SS "def src\&.c\&.Teleporteur\&.Teleporteur\&.teleporterVoiture ( voiture,  place)\fC [static]\fP"

.PP
Teleportation d'une Voiture d'un Client standard\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvoiture\fP Voiture a garer 
.br
\fIplace\fP Place ou garer la vViture 
.RE
.PP
\fBReturns:\fP
.RS 4
Placement cree 
.RE
.PP

.SS "def src\&.c\&.Teleporteur\&.Teleporteur\&.teleporterVoitureSuperAbonne ( voiture,  parking)\fC [static]\fP"

.PP
Teleportation d'une Voiture d'un superAbo\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvoiture\fP Voiture a garer 
.br
\fIparking\fP \fBParking\fP ou garer la Voiture 
.RE
.PP
\fBReturns:\fP
.RS 4
Placement cree 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Dream Park from the source code\&.
