.TH "src.m.test.TestService.TestService" 3 "Sun Feb 8 2015" "Version 1.0" "Dream Park" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.m.test.TestService.TestService \- Test des Service\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBTestService\fP (self)"
.br
.RI "\fITest instanciation\&. \fP"
.ti -1c
.RI "def \fBTestModifService\fP (self)"
.br
.RI "\fITest modification service\&. \fP"
.ti -1c
.RI "def \fBTestDoService\fP (self)"
.br
.RI "\fITest realisation service\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Test des Service\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Dream Park from the source code\&.
