.TH "src.v.Camera.Camera" 3 "Sun Feb 8 2015" "Version 1.0" "Dream Park" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.v.Camera.Camera \- Une \fBCamera\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBdonnerVoiture\fP ()"
.br
.RI "\fIRetourne une voiture genere aleatoirement de longueur entre 150 et 300 cm et de hauteur entre 100 et 200 cm\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Une \fBCamera\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Dream Park from the source code\&.
