.TH "src.v.MyQt.MyQMainWindow" 3 "Sun Feb 8 2015" "Version 1.0" "Dream Park" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.v.MyQt.MyQMainWindow \- QMainWindow personnalisé  

.SH SYNOPSIS
.br
.PP
.PP
Inherits QMainWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBcloseEvent\fP (self, event)"
.br
.RI "\fIAjout d'une boite de dialogue a la fermeture de la fenetre\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
QMainWindow personnalisé 

.SH "Author"
.PP 
Generated automatically by Doxygen for Dream Park from the source code\&.
