.TH "src.v.Ui_Admin" 3 "Sun Feb 8 2015" "Version 1.0" "Dream Park" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.v.Ui_Admin \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUi_CreaParking\fP"
.br
.RI "\fIUI de creatoin de parking\&. \fP"
.ti -1c
.RI "class \fBUi_MainWindow\fP"
.br
.RI "\fIUI page principal d'administration\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB_fromUtf8\fP = QtCore\&.QString\&.fromUtf8"
.br
.ti -1c
.RI "\fB_encoding\fP = QtGui\&.QApplication\&.UnicodeUTF8"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    Module des classes d'affichage UI generés par QtDesigner pour les UI Admin

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Dream Park from the source code\&.
