.TH "src.v.Ui_CreaParking.Ui_CreaParking" 3 "Fri Feb 6 2015" "Version 0.1" "Dream Park" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.v.Ui_CreaParking.Ui_CreaParking \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsetupUi\fP (self, CreaParking)"
.br
.ti -1c
.RI "def \fBretranslateUi\fP (self, CreaParking)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlayoutWidget\fP"
.br
.ti -1c
.RI "\fBhorizontalLayout_2\fP"
.br
.ti -1c
.RI "\fBbtn_annuler\fP"
.br
.ti -1c
.RI "\fBbtn_valider\fP"
.br
.ti -1c
.RI "\fBtableWidget\fP"
.br
.ti -1c
.RI "\fBbtn_addRow\fP"
.br
.ti -1c
.RI "\fBbtn_rmRow\fP"
.br
.ti -1c
.RI "\fBlayoutWidget1\fP"
.br
.ti -1c
.RI "\fBhorizontalLayout\fP"
.br
.ti -1c
.RI "\fBverticalLayout\fP"
.br
.ti -1c
.RI "\fBlabel\fP"
.br
.ti -1c
.RI "\fBverticalLayout_2\fP"
.br
.ti -1c
.RI "\fBlineEdit_nom\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Dream Park from the source code\&.
