.TH "src.m.TypePlace.TypePlace" 3 "Mon Jan 12 2015" "Version 0.1" "Dream Park" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.m.TypePlace.TypePlace \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, h, l, nb)"
.br
.ti -1c
.RI "def \fBhauteur\fP (self)"
.br
.ti -1c
.RI "def \fBlongueur\fP (self)"
.br
.ti -1c
.RI "def \fBnb\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    Classe qui permet de définir un type de place

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Dream Park from the source code\&.
