.TH "src.v.MyQt.MyQWidget" 3 "Sun Feb 8 2015" "Version 1.0" "Dream Park" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.v.MyQt.MyQWidget \- QWydget personnalisé  

.SH SYNOPSIS
.br
.PP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, main)"
.br
.RI "\fIAjout d'un controleur parent en parametre lors de la creation d'un Qwidget\&. \fP"
.ti -1c
.RI "def \fBcloseEvent\fP (self, event)"
.br
.RI "\fIAjout d'une boite de dialogue a la fermeture de la fenetre\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
QWydget personnalisé 

.SH "Author"
.PP 
Generated automatically by Doxygen for Dream Park from the source code\&.
