.TH "v.MyQWidget.MyQWidget" 3 "Thu Feb 5 2015" "Version 0.1" "Dream Park" \" -*- nroff -*-
.ad l
.nh
.SH NAME
v.MyQWidget.MyQWidget \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, main)"
.br
.ti -1c
.RI "def \fBcloseEvent\fP (self, event)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Dream Park from the source code\&.
