.TH "v.Ui_Borne.Ui_Borne" 3 "Thu Feb 5 2015" "Version 0.1" "Dream Park" \" -*- nroff -*-
.ad l
.nh
.SH NAME
v.Ui_Borne.Ui_Borne \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsetupUi\fP (self, Borne)"
.br
.ti -1c
.RI "def \fBretranslateUi\fP (self, Borne)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBbtn_Voiture\fP"
.br
.ti -1c
.RI "\fBnomParking\fP"
.br
.ti -1c
.RI "\fBbox_id\fP"
.br
.ti -1c
.RI "\fBlayoutWidget\fP"
.br
.ti -1c
.RI "\fBhorizontalLayout\fP"
.br
.ti -1c
.RI "\fBverticalLayout_2\fP"
.br
.ti -1c
.RI "\fBlabel\fP"
.br
.ti -1c
.RI "\fBlineEdit_id\fP"
.br
.ti -1c
.RI "\fBbtn_validerID\fP"
.br
.ti -1c
.RI "\fBverticalLayout\fP"
.br
.ti -1c
.RI "\fBlabIdClient\fP"
.br
.ti -1c
.RI "\fBbox_abo\fP"
.br
.ti -1c
.RI "\fBformLayoutWidget\fP"
.br
.ti -1c
.RI "\fBformLayout\fP"
.br
.ti -1c
.RI "\fBnomLabel\fP"
.br
.ti -1c
.RI "\fBnomLineEdit\fP"
.br
.ti -1c
.RI "\fBprenomLabel\fP"
.br
.ti -1c
.RI "\fBnumeroCarteLabel\fP"
.br
.ti -1c
.RI "\fBnumeroCarteLineEdit\fP"
.br
.ti -1c
.RI "\fBprenomLineEdit\fP"
.br
.ti -1c
.RI "\fBcheckBox\fP"
.br
.ti -1c
.RI "\fBbtn_valider_abo\fP"
.br
.ti -1c
.RI "\fBbtn_desabo\fP"
.br
.ti -1c
.RI "\fBbox_recup\fP"
.br
.ti -1c
.RI "\fBformLayoutWidget_2\fP"
.br
.ti -1c
.RI "\fBformLayout_2\fP"
.br
.ti -1c
.RI "\fBnumeroTicketLabel\fP"
.br
.ti -1c
.RI "\fBnumeroTicketLineEdit\fP"
.br
.ti -1c
.RI "\fBbtn_recuperer\fP"
.br
.ti -1c
.RI "\fBpushButton\fP"
.br
.ti -1c
.RI "\fBlabel_aff\fP"
.br
.ti -1c
.RI "\fBbox_garer\fP"
.br
.ti -1c
.RI "\fBbtn_garer\fP"
.br
.ti -1c
.RI "\fBbox_service\fP"
.br
.ti -1c
.RI "\fBdateTimeEdit\fP"
.br
.ti -1c
.RI "\fBlayoutWidget_2\fP"
.br
.ti -1c
.RI "\fBverticalLayout_4\fP"
.br
.ti -1c
.RI "\fBcheckBox_Livraison_2\fP"
.br
.ti -1c
.RI "\fBcheckBox_Maintenance_2\fP"
.br
.ti -1c
.RI "\fBcheckBox_Entretien_2\fP"
.br
.ti -1c
.RI "\fBformLayoutWidget_3\fP"
.br
.ti -1c
.RI "\fBformLayout_4\fP"
.br
.ti -1c
.RI "\fBlieuLabel_2\fP"
.br
.ti -1c
.RI "\fBlieuLineEdit_2\fP"
.br
.ti -1c
.RI "\fBbtn_annuler\fP"
.br
.ti -1c
.RI "\fBbtn_quitter\fP"
.br
.ti -1c
.RI "\fBlcdNumber\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Dream Park from the source code\&.
