.TH "v.Ui_MainWindow.Ui_MainWindow" 3 "Thu Feb 5 2015" "Version 0.1" "Dream Park" \" -*- nroff -*-
.ad l
.nh
.SH NAME
v.Ui_MainWindow.Ui_MainWindow \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsetupUi\fP (self, MainWindow)"
.br
.ti -1c
.RI "def \fBretranslateUi\fP (self, MainWindow)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcentralwidget\fP"
.br
.ti -1c
.RI "\fBtabWidget\fP"
.br
.ti -1c
.RI "\fBtab\fP"
.br
.ti -1c
.RI "\fBlabel\fP"
.br
.ti -1c
.RI "\fBlistWidget\fP"
.br
.ti -1c
.RI "\fBtab_2\fP"
.br
.ti -1c
.RI "\fBverticalLayout\fP"
.br
.ti -1c
.RI "\fBformLayout_3\fP"
.br
.ti -1c
.RI "\fBlabel_13\fP"
.br
.ti -1c
.RI "\fBnom\fP"
.br
.ti -1c
.RI "\fBlabel_15\fP"
.br
.ti -1c
.RI "\fBplacesParNiveau\fP"
.br
.ti -1c
.RI "\fBlabel_16\fP"
.br
.ti -1c
.RI "\fBplacesDispo\fP"
.br
.ti -1c
.RI "\fBlabel_17\fP"
.br
.ti -1c
.RI "\fBplacesSuperAbo\fP"
.br
.ti -1c
.RI "\fBhorizontalLayout\fP"
.br
.ti -1c
.RI "\fBbtn_details\fP"
.br
.ti -1c
.RI "\fBbtn_borne\fP"
.br
.ti -1c
.RI "\fBbtn_creer\fP"
.br
.ti -1c
.RI "\fBbtn_supprimer\fP"
.br
.ti -1c
.RI "\fBtab_3\fP"
.br
.ti -1c
.RI "\fBgroupBox\fP"
.br
.ti -1c
.RI "\fBcomboBox_maintenance\fP"
.br
.ti -1c
.RI "\fBbtn_effectuer_maintenance\fP"
.br
.ti -1c
.RI "\fBgroupBox_2\fP"
.br
.ti -1c
.RI "\fBcomboBox_entretien\fP"
.br
.ti -1c
.RI "\fBbtn_effectuer_entretien\fP"
.br
.ti -1c
.RI "\fBgroupBox_3\fP"
.br
.ti -1c
.RI "\fBcomboBox_livraison\fP"
.br
.ti -1c
.RI "\fBbtn_effectuer_livraison\fP"
.br
.ti -1c
.RI "\fBtab_4\fP"
.br
.ti -1c
.RI "\fBlabel_2\fP"
.br
.ti -1c
.RI "\fBlabel_3\fP"
.br
.ti -1c
.RI "\fBlabel_4\fP"
.br
.ti -1c
.RI "\fBcomboBox\fP"
.br
.ti -1c
.RI "\fBmenubar\fP"
.br
.ti -1c
.RI "\fBmenuFichier\fP"
.br
.ti -1c
.RI "\fBmenuA_propos\fP"
.br
.ti -1c
.RI "\fBstatusbar\fP"
.br
.ti -1c
.RI "\fBactionCharger\fP"
.br
.ti -1c
.RI "\fBactionSauvegarder\fP"
.br
.ti -1c
.RI "\fBactionAfficher\fP"
.br
.ti -1c
.RI "\fBactionNouveau\fP"
.br
.ti -1c
.RI "\fBactionRechercher\fP"
.br
.ti -1c
.RI "\fBactionListe\fP"
.br
.ti -1c
.RI "\fBactionAjouter\fP"
.br
.ti -1c
.RI "\fBactionQuitter\fP"
.br
.ti -1c
.RI "\fBaction\fP"
.br
.ti -1c
.RI "\fBactionNouveau_2\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Dream Park from the source code\&.
